class:
  http:
    addr: ":18000"
  elasticsearch:
    keepDataAfterRestart: true
  proxyStudentID: "xxxxxxxxxx"
  selectionUploadToken: "replace-with-a-long-random-token"
  dataAliveDays: 1

log:
  path: "/logs/app.log"
  maxSize: 100
  maxBackups: 7
  maxAge: 30
  compress: true
