// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/ccnubox-be/be-class_v2/biz/usecase"
	"github.com/asynccnu/ccnubox-be/be-class_v2/client"
	"github.com/asynccnu/ccnubox-be/be-class_v2/conf"
	"github.com/asynccnu/ccnubox-be/be-class_v2/cron"
	"github.com/asynccnu/ccnubox-be/be-class_v2/grpc"
	"github.com/asynccnu/ccnubox-be/be-class_v2/http"
	"github.com/asynccnu/ccnubox-be/be-class_v2/ioc"
	"github.com/asynccnu/ccnubox-be/be-class_v2/repository"
	"github.com/asynccnu/ccnubox-be/be-class_v2/repository/lock"
	"github.com/asynccnu/ccnubox-be/be-class_v2/service"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	infraConf := conf.InitInfraConfig()
	serverConf := conf.InitServerConf()
	logger := ioc.InitLogger(serverConf)
	elasticClient, err := repository.NewEsClient(infraConf, serverConf, logger)
	if err != nil {
		return nil, nil, err
	}
	classData, cleanup, err := repository.NewClassData(elasticClient, logger)
	if err != nil {
		return nil, nil, err
	}
	clientv3Client := ioc.InitEtcdClient(infraConf)
	classerClient := ioc.InitClassListClient(clientv3Client, infraConf)
	classListService := client.NewClassListService(classerClient, logger)
	redisClient := ioc.InitRedis(infraConf)
	builder := lock.NewRedisLockBuilder(redisClient)
	cache := repository.NewCache(redisClient)
	classServiceUserCase := usecase.NewClassServiceUserCase(classData, classListService, builder, cache, logger)
	userServiceClient := ioc.InitUserClient(clientv3Client, infraConf)
	userService := client.NewUserService(userServiceClient, logger)
	db := ioc.InitDB(infraConf)
	cultivateStrategyData := repository.NewCultivateStrategyData(db, serverConf)
	proxyClient := ioc.InitProxyClient(clientv3Client, infraConf)
	client2 := ioc.InitHTTPProxyClient(proxyClient, infraConf, logger)
	cultivateStrategyBiz := usecase.NewCultivateStrategyBiz(userService, cache, cultivateStrategyData, client2, logger)
	classService := service.NewClassService(classServiceUserCase, cultivateStrategyBiz)
	freeClassroomData := repository.NewFreeClassroomData(elasticClient, logger)
	freeClassroomBiz := usecase.NewFreeClassroomBiz(classData, freeClassroomData, userService, builder, cache, client2, logger)
	classroomJSONData := repository.NewClassroomJSONData()
	freeClassroomService := service.NewFreeClassroomService(freeClassroomBiz, classroomJSONData)
	classServer := grpc.NewClassServer(classService, freeClassroomService)
	server := ioc.InitGRPCServer(classServer, clientv3Client, logger, infraConf)
	selectionUploader := http.NewSelectionUploader(freeClassroomBiz)
	classroomJSONSvc := http.NewClassroomJSONSvc(classroomJSONData)
	handler := http.NewHandler(selectionUploader, classroomJSONSvc)
	httpServer := ioc.InitHTTPServer(handler, serverConf)
	metricsxServer := ioc.InitMetricsServer(infraConf)
	task := cron.NewTask(classServiceUserCase, freeClassroomBiz, classListService, serverConf, logger)
	v := ioc.InitOTel(infraConf)
	app := NewApp(server, httpServer, metricsxServer, task, v, logger)
	return app, func() {
		cleanup()
	}, nil
}
